name: First Workflow

on: 
  push:
    branches:
      - master


jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first GitHub Action Workflow"

      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: List repo files
        run: ls -la
